export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const FETCH_QUIZ_REQUEST= "FETCH_QUIZ_REQUEST"
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS"
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE"

export const SUBMIT_ANSWER = "SUBMIT_ANSWER"
export const SKIP_QUESTION = "SKIP_QUESTION"

export const AI_QUIZ_REQUEST= "AI_QUIZ_REQUEST"
export const AI_QUIZ_SUCCESS ="AI_QUIZ_SUCCESS"
export const AI_QUIZ_FAILURE ="AI_QUIZ_FAILURE"
export const AI_SUBMIT_ANSWER = "AI_SUBMIT_ANSWER"